### ISSUE TITLE
SEGFAULT on empty HTTP POST requests

### ISSUE THREAD

**Issue by mpeee** [eddic/fastcgipp#18]
it does segfault in http.cpp, fastcgipp version 2.1 in 
void Fastcgipp::Http::Environment<charT>::parsePostsUrlEncoded()

I did not figured out how to fix it yet.

**Comment by aggsol** [comment]
This short article might help you finde the cvause/fix. https://ericlippert.com/2014/03/05/how-to-debug-small-programs/

**Comment by eddic** [comment]
Does this same issue occur with 3.0beta? My interest in fixing 2.1 is somewhat waning.

**Comment by Erroneous1** [comment]
I'm not sure it would occur even on 2.x branch anymore. I had a patch for http.cpp from before you moved to github that added `if(nameStart == 0)return;` after line 430 (I'm guessing currently around 437 now). I don't think that's necessary anymore because you have `if(!postBuffer)return;`. My patch was for [2.1](http://download.savannah.nongnu.org/releases/fastcgipp/fastcgi++-2.1.tar.bz2) which did not check postBuffer.

**Comment by eddic** [comment]
Yeah I think we can lay this one to rest.
