### ISSUE TITLE
Poll gave fd xx which isn't in m_sockets

### ISSUE THREAD

**Issue by ZhangzheBJUT** [eddic/fastcgipp#28]
I came across this problem sometimes.
`Jul 10 00:00:03  machinename /fastcgidemo [1452] [error]: Poll gave fd 26 which isn't in m_sockets.`
It was likely that socket gourps was in disorder.i want to know what can lead to this error and how to solve.

**Comment by eddic** [comment]
Yeah. This is a tough one. I'd guess that the OS just isn't cleaning things up as quickly as fastcgi++ is expecting it to. I myself have never run into this issue but I suspect different system configurations have different socket cleanup strategies. In all fairness it's probably not worth even throwing an error message since the code tries again to fully clean things up. It's more just intended to notify you that, although everything is okay, something happened that was unexpected.

Are your systems Linux epoll() or posix select()?

**Comment by eddic** [comment]
Again, thanks @Erroneous1 for solving this one.

**Comment by Erroneous1** [comment]
No problem. I'm in the process of updating my 2.1 code to 3.0. So far I am loving the improvements!

**Comment by eddic** [comment]
Ah glad to hear it! Let me know once you feel it is running smoothly and we'll do a 3.1 "Aaron" release with all your fixes.

**Comment by ZhangzheBJUT** [comment]
Excellent! i expect your good news! @Erroneous1
