### ISSUE TITLE
Session Problem

### ISSUE THREAD

**Issue by Yemor** [eddic/fastcgipp#57]
I seem found a problem with the Session Example.
Session.fcgi were not share the s_sessions in different process.
I had open 25 process to launch the Session.fcgi ,
When I reflash the Site too fast , the nginx will use other process(because the first process is using)
and then the session size is zero in second process.

**Comment by Yemor** [comment]
Maybe you can solve it by make a shared memory at linux system.

**Comment by Yemor** [comment]
Thank for your library. It is work successful at one process. I just try to know how to Identify same sid between different process. :P Thank for you help.

**Comment by Yemor** [comment]
Or maybe we can use Redis to save the session?

**Comment by eddic** [comment]
The fastcgi++ API is not intended for the application to be spread across multiple instances. The motivation for nginx spawning multiple instances is in response to badly made FastCGI applications not scaling well. Fastcgi++ applications _do_ scale well. The solution to your problem is to modify your nginx configuration to ensure it never spawns more than a single instance.

**Comment by Yemor** [comment]
Ok, thank for your reply, that is helpful!
